[manager]
prepend_keymap = [
  { on = [
    "E",
  ], run = "plugin eza-preview", desc = "Toggle tree/list dir preview" },
  { on = [
    "-",
  ], run = "plugin eza-preview '--inc-level'", desc = "Increment tree level" },
  { on = [
    "_",
  ], run = "plugin eza-preview '--dec-level'", desc = "Decrement tree level" },
  { on = [
    "$",
  ], run = "plugin eza-preview '--toggle-follow-symlinks'", desc = "Toggle tree follow symlinks" },
  { on = [
    "l",
  ], run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
  { on = [
    "c",
    "a",
  ], run = "plugin compress", desc = "Archive selected files" },
  { on = [
    "T",
  ], run = "plugin toggle-pane max-preview", desc = "Maximize or restore the preview pane" },
  { on = [
    "F",
  ], run = "plugin smart-filter", desc = "Smart filter" },
  { on = [
    "m",
  ], run = "plugin relative-motions", desc = "Trigger a new relative motion" },
  { on = [
    "1",
  ], run = "plugin relative-motions 1", desc = "Move in relative steps" },
  { on = [
    "2",
  ], run = "plugin relative-motions 2", desc = "Move in relative steps" },
  { on = [
    "3",
  ], run = "plugin relative-motions 3", desc = "Move in relative steps" },
  { on = [
    "4",
  ], run = "plugin relative-motions 4", desc = "Move in relative steps" },
  { on = [
    "5",
  ], run = "plugin relative-motions 5", desc = "Move in relative steps" },
  { on = [
    "6",
  ], run = "plugin relative-motions 6", desc = "Move in relative steps" },
  { on = [
    "7",
  ], run = "plugin relative-motions 7", desc = "Move in relative steps" },
  { on = [
    "8",
  ], run = "plugin relative-motions 9", desc = "Move in relative steps" },
  { on = [
    "9",
  ], run = "plugin relative-motions 9", desc = "Move in relative steps" },
  { on = [
    "M",
  ], run = "plugin mount", desc = "disk mount" },
]
